const DATA = [
  {
    id: 0,
    title: "Iphone 11",
    price: 500,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphon11.jpg",
  },
  
  {
    id: 2,
    title: "Iphone 12",
    price: 600,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphone12.jpeg",
  },
  {
    id: 1,
    title: "Iphone 14 promax",
    price: 800,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphone14min.jpeg",
  },
  {
    id: 3,
    title: "Iphone 12",
    price: 600,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphone12.jpeg",
  },
  {
    id: 4,
    title: "Iphone X",
    price: 350,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphonex.png",
  },
  {
    id: 15,
    title: "Iphone 12",
    price: 600,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphone12.jpeg",
  },
  {
    id: 6,
    title: "Iphone 11",
    price: 500,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphon11.jpg",
  },
  {
    id: 7,
    title: "Iphone 14 mini",
    price: 700,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphone14min.jpeg",
  },
  {
    id: 8,
    title: "Iphone SE",
    price: 400,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphonese.jpeg",
  },
  {
    id: 9,
    title: "Iphone 13",
    price: 650,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphon13.jpeg",
  },
  {
    id: 16,
    title: "Iphone 11",
    price: 500,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphon11.jpg",
  },
  {
    id: 10,
    title: "Iphone 14 Pro",
    price: 800,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphone14pro.jpeg",
  },
  {
    id: 11,
    title: "Iphone 12",
    price: 600,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphone12.jpeg",
  },
  {
    id: 12,
    title: "Iphone 13",
    price: 600,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphon13.jpeg",
  },
  {
    id: 13,
    title: "Iphone 11",
    price: 500,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphon11.jpg",
  },
  {
    id: 14,
    title: "Iphone 12",
    price: 900,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphone12.jpeg",
  },
  {
    id: 5,
    title: "Iphone X",
    price: 350,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphonex.png",
  },
  {
    id: 17,
    title: "Iphone SE",
    price: 450,
    desc: "contrary to popular belief, lorem ipsum is not simply random text. It hasroots in a piece of classical latin literature from 45Bc, making it over 2000 years old, a latin professor named Richard Mclintock at hampden sydney college in virginia, looked up one of more obscure latin words consecuteur, from a lorem ipsum passage, and going through the cities of the world in classical literature, discovered the undoubtful source.",
    img: "/assets/images/products/iphonese.jpeg",
  },
];

export default DATA;
