const DATA = [
  {
    id: 0,
    title: "Iphone 11",
    price: 400,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphon11.jpg",
    countinstock: 3,
    rating: 4,
    numreviews: 3, 
  },
  
  {
    id: 1,
    title: "Iphone 12",
    price: 700,
    desc: "128Gb | 12mp |",
    img: "/assets/images/products/iphone12.jpeg",
  },
  {
    id: 2,
    title: "Iphone 14 promax",
    price: 800,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphone14min.jpeg",
  },
  {
    id: 3,
    title: "Iphone 12",
    price: 600,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphone12.jpeg",
  },
  {
    id: 4,
    title: "Iphone X",
    price: 350,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphonex.png",
  },
  {
    id: 5,
    title: "Iphone 12",
    price: 600,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphone12.jpeg",
  },
  {
    id: 6,
    title: "Iphone 11",
    price: 500,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphon11.jpg",
  },
  {
    id: 7,
    title: "Iphone 14 mini",
    price: 1000,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphone14min.jpeg",
  },
  {
    id: 8,
    title: "Iphone SE",
    price: 2400,
    desc: "1Tb | 12mp |",
    img: "/assets/images/products/iphonese.jpeg",
  },
  {
    id: 9,
    title: "Iphone 13",
    price: 650,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphon13.jpeg",
  },
  {
    id: 10,
    title: "Iphone 11",
    price: 500,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphon11.jpg",
  },
  {
    id: 11,
    title: "Iphone 14 Pro",
    price: 800,
    desc: "128Gb | 12mp |",
    img: "/assets/images/products/iphone14pro.jpeg",
  },
  {
    id: 12,
    title: "Iphone 12",
    price: 600,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphone12.jpeg",
  },
  {
    id: 13,
    title: "Iphone 13",
    price: 600,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphon13.jpeg",
  },
  {
    id: 14,
    title: "Iphone 11",
    price: 500,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphon11.jpg",
  },
  {
    id: 15,
    title: "Iphone 12",
    price: 900,
    desc: "512Gb | 12mp |",
    img: "/assets/images/products/iphone12.jpeg",
  },
  {
    id: 16,
    title: "Iphone X",
    price: 350,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/iphonex.png",
  },
  {
    id: 17,
    title: "Iphone SE",
    price: 450,
    desc: "128Gb | 12mp | ",
    img: "/assets/images/products/iphonese.jpeg",
  },
  {
    id: 18,
    title: "Airpods",
    price: 450,
    desc: "pods",
    img: "/assets/images/products/airpods.jpg",
  },
  {
    id: 19,
    title: "Alexa",
    price: 450,
    desc: "Alexa",
    img: "/assets/images/products/alexa.jpg",
  },
  {
    id: 20,
    title: "Apple",
    price: 450,
    desc: "Apple",
    img: "/assets/images/products/Apple.jpg",
  },
  {
    id: 21,
    title: "Camera",
    price: 450,
    desc: "camera",
    img: "/assets/images/products/camera.jpg",
  },
  {
    id: 22,
    title: "Mouse",
    price: 150,
    desc: "portable mouse",
    img: "/assets/images/products/mouse.jpg",
  },
  {
    id: 23,
    title: "PlayStation",
    price: 1150,
    desc: "white",
    img: "/assets/images/products/playstation.jpg",
  },
  {
    id: 24,
    title: "Iphone 11",
    price: 450,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/red.jpg",
  },
  {
    id: 25,
    title: "TV",
    price: 950,
    desc: "Touchscreen LED",
    img: "/assets/images/products/tv.png",
  },
  {
    id: 26,
    title: "Samsung",
    price: 450,
    desc: "64Gb | 12mp | Black",
    img: "/assets/images/products/sansungnote.png",
  },
  {
    id: 27,
    title: "Iphone",
    price: 450,
    desc: "64Gb | 12mp | Black",
    img: "/assets/images/products/phone.jpg",
  },
  {
    id: 28,
    title: "Samsung Note9",
    price: 450,
    desc: "64Gb | samsung | Black",
    img: "/assets/images/products/note9.jpg",
  },
  {
    id: 29,
    title: "Midnight grey Iphone",
    price: 450,
    desc: "512Gb | 12mp |",
    img: "/assets/images/products/midnight.png",
  },
  {
    id: 30,
    title: "Home Theatre",
    price: 450,
    desc: "Quality sound Black",
    img: "/assets/images/products/hometeata.jpg",
  },
  {
    id: 31,
    title: "Grey Iphone",
    price: 450,
    desc: "256Gb | 12mp |",
    img: "/assets/images/products/grey2.jpg",
  },
  {
    id: 32,
    title: "Grey Iphone",
    price: 450,
    desc: "128Gb | 12mp | ",
    img: "/assets/images/products/grey.jpg",
  },
  {
    id: 33,
    title: "Camon",
    price: 450,
    desc: "Camera",
    img: "/assets/images/products/camon.JPG",
  },
  {
    id: 34,
    title: "Camera",
    price: 450,
    desc: "Camera",
    img: "/assets/images/products/cameranik.jpg",
  },
  {
    id: 35,
    title: "Airpod black",
    price: 450,
    desc: "Airpod Black",
    img: "/assets/images/products/airpodss.jpg",
  },
  {
    id: 36,
    title: "LED flatscreen TV",
    price: 450,
    desc: "LED",
    img: "/assets/images/products/40inch.jpg",
  },
  {
    id: 37,
    title: "Iphone 11 Orange",
    price: 450,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/11orange.jpg",
  },
  {
    id: 38,
    title: "PlayStation",
    price: 450,
    desc: "gamepad with 2 games",
    img: "/assets/images/products/playstation.jpg",
  },
  {
    id: 39,
    title: "Samsung Note 10",
    price: 450,
    desc: "64Gb | 12mp |",
    img: "/assets/images/products/notee.jpg",
  },
];

export default DATA;
